def generate_html_report(user, analysis, books):
    """
    PDF 대신 HTML 파일 생성 후 다운로드하는 방식
    (브라우저에서 PDF 변환 가능)
    """

    html = f"""
    <html>
    <head>
        <meta charset="UTF-8" />
        <style>
            body {{
                font-family: 'Noto Sans KR', sans-serif;
                margin: 40px;
                line-height: 1.7;
            }}
            h1 {{
                color: #16499A;
                font-size: 32px;
                text-align: center;
                margin-bottom: 10px;
            }}
            h2 {{
                color: #16499A;
                border-bottom: 2px solid #16499A;
                padding-bottom: 5px;
                margin-top: 40px;
            }}
            .info {{
                font-size: 16px;
                margin-top: 20px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }}
            th {{
                background: #16499A;
                color: white;
                padding: 8px;
                border: 1px solid #888;
            }}
            td {{
                padding: 8px;
                border: 1px solid #888;
                vertical-align: top;
            }}
            .section {{
                margin-top: 20px;
            }}
        </style>
    </head>

    <body>

        <h1>학생부 맞춤형 분석 리포트</h1>

        <div class="info">
            <b>이름:</b> {user['name']}<br/>
            <b>학교:</b> {user['school']}<br/>
            <b>지원 학년도:</b> {user['year']}<br/>
        </div>

        <h2>📘 종합 분석 요약</h2>

        <div class="section">
            <b>한 줄 요약:</b><br/>
            {analysis['summary']}<br/><br/>

            <b>강점:</b><br/>
            {'<br/>'.join('- ' + s for s in analysis['strengths'])}<br/><br/>

            <b>약점:</b><br/>
            {'<br/>'.join('- ' + w for w in analysis['weaknesses'])}<br/><br/>

            <b>3학년 보완 전략:</b><br/>
            - 프로젝트: {', '.join(analysis['suggestions']['projects'])}<br/>
            - 보고서 주제: {', '.join(analysis['suggestions']['reports'])}<br/>
            - 추천 독서: {', '.join(analysis['suggestions']['books'])}<br/>
            - 학급/학년 활동: {analysis['suggestions']['class_activity']}<br/>
            - 리더십/협력: {analysis['suggestions']['leadership']}<br/>
        </div>

        <h2>📚 독서활동 분석</h2>

        <table>
            <tr>
                <th>도서명</th>
                <th>저자</th>
                <th>핵심 요약</th>
                <th>전공 연계</th>
                <th>프로젝트 제안</th>
            </tr>
    """

    # 테이블 행 추가
    for b in books:
        html += f"""
            <tr>
                <td>{b['title']}</td>
                <td>{b['author']}</td>
                <td>{"<br/>".join(b['summary']['summary_text'])}</td>
                <td>{"<br/>".join(b['summary']['major_links'])}</td>
                <td>{"<br/>".join(b['summary']['projects'])}</td>
            </tr>
        """

    html += """
        </table>

        <br/><br/>
        <div style="text-align:center; font-size:12px; color:#666;">
            Generated by AI Student Record Analyzer
        </div>

    </body>
    </html>
    """

    return html.encode("utf-8")
