import re
import os
import io
import zipfile
import pandas as pd
from xhtml2pdf import pisa


# ============================================
# 1) 생기부 섹션 자동 분리
# ============================================
def parse_student_record(text):

    patterns = {
        "자율활동": r"자율활동([\s\S]*?)동아리활동",
        "창체동아리": r"동아리활동([\s\S]*?)진로활동",
        "진로활동": r"진로활동([\s\S]*?)창의적 체험활동상황",
        "교과학습발달상황": r"교과학습발달상황([\s\S]*?)세부능력 및 특기사항",
        "교과별 세부능력 특기사항": r"세부능력 및 특기사항([\s\S]*?)독서활동",
        "독서활동": r"독서활동([\s\S]*?)행동특성 및 종합의견",
        "행동특성및종합의견": r"행동특성 및 종합의견([\s\S]*)"
    }

    result = {}
    for key, pattern in patterns.items():
        match = re.search(pattern, text)
        result[key] = match.group(1).strip() if match else "(해당 항목 없음)"

    return result


# ============================================
# 2) 독서활동 자동 추출
# ============================================
def extract_books(text):
    """
    생기부 독서활동에서 도서명 / 저자 / 학생 의견 자동 추출
    패턴 예: 1984(조지오웰) ... 내용
    """

    pattern = r"([^\n]+?)\(([^)]+)\)\s*(.+?)(?=\n|$)"
    books = []

    for title, author, content in re.findall(pattern, text):
        books.append({
            "title": title.strip(),
            "author": author.strip(),
            "student_note": content.strip()
        })

    return books


# ============================================
# 3) PDF 생성
# ============================================
def generate_pdf(user, analysis, books):
    df = pd.DataFrame([
        {
            "도서명": b["title"],
            "저자": b["author"],
            "요약": " / ".join(b["summary"]["summary_text"]),
            "전공 연계": " / ".join(b["summary"]["major_links"]),
            "프로젝트 제안": " / ".join(b["summary"]["projects"]),
        }
        for b in books
    ])

    table_html = df.to_html(index=False, escape=False)

    # ------------------------
    # HTML 템플릿
    # ------------------------
    html = f"""
    <html>
    <head>
        <meta charset="UTF-8" />
        <style>
            body {{
                font-family: 'Noto Sans KR';
                font-size: 13px;
                line-height: 1.6;
            }}
            h1 {{
                color: #16499A;
            }}
            h2 {{
                color: #16499A;
                border-bottom: 2px solid #16499A;
                padding-bottom: 4px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }}
            th, td {{
                border: 1px solid #333;
                padding: 8px;
                font-size: 11px;
            }}
            th {{
                background-color: #efefef;
            }}
        </style>
    </head>

    <body>
        <h1>함창고 맞춤형 학생부 분석 리포트</h1>

        <h2>학생 기본 정보</h2>
        <p><b>이름:</b> {user["name"]}<br>
           <b>학교:</b> {user["school"]}<br>
           <b>지원학년도:</b> {user["year"]}</p>

        <h2>AI 종합 분석 요약</h2>
        <pre>{analysis}</pre>

        <h2>독서 활동 분석</h2>
        {table_html}

        <br><br>
        <p style="text-align:center; font-size:12px; color:#666;">
            Generated by AI Student Record Analyzer
        </p>
    </body>
    </html>
    """

    # PDF 변환
    pdf_buffer = io.BytesIO()
    pisa.CreatePDF(io.StringIO(html), dest=pdf_buffer)

    return pdf_buffer.getvalue()


# ============================================
# 4) 관리자 ZIP 다운로드
# ============================================
def admin_zip_download():
    if not os.path.exists("reports"):
        os.makedirs("reports")

    zip_path = "all_reports.zip"
    with zipfile.ZipFile(zip_path, "w") as z:
        for f in os.listdir("reports"):
            z.write(f"reports/{f}")

    return zip_path
